// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSX7R4JV_nrqJ5ng8-Ut2SeInamsOGU2c',
    appId: '1:453296497364:web:734d31db2ffdc3591dd141',
    messagingSenderId: '453296497364',
    projectId: 'hostel-management-system-60f0f',
    authDomain: 'hostel-management-system-60f0f.firebaseapp.com',
    storageBucket: 'hostel-management-system-60f0f.firebasestorage.app',
    measurementId: 'G-DBR2ZWKH8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzIhDcGjrt6IQ4YGIObpnoIT7-oxfSeM',
    appId: '1:453296497364:android:54e178cbff5f55af1dd141',
    messagingSenderId: '453296497364',
    projectId: 'hostel-management-system-60f0f',
    storageBucket: 'hostel-management-system-60f0f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSX7R4JV_nrqJ5ng8-Ut2SeInamsOGU2c',
    appId: '1:453296497364:web:88294e7d5455d4a51dd141',
    messagingSenderId: '453296497364',
    projectId: 'hostel-management-system-60f0f',
    authDomain: 'hostel-management-system-60f0f.firebaseapp.com',
    storageBucket: 'hostel-management-system-60f0f.firebasestorage.app',
    measurementId: 'G-3J2KT50RCZ',
  );
}
